### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by supritashankar** [vmaudgalya/projects#1]
In the README https://github.com/vmaudgalya/projects/blob/master/CommitCountParser.java#L7
you need to mention that one needs to be inside the git repository for which they want stats. Like
1. cd <into-git-repository>
2. git log ...
You might think its a no-brainer :P .. but its nice to have it there. its helpful when the brain does not work :)

And good work :+1:

**Comment by vmaudgalya** [comment]
@supritashankar thanks for your feedback!
